-- Kilvio FIT - RPC POS transaccional
-- Paso 3: confirmar venta desde carrito local.
-- Este script no borra datos, no desactiva RLS y no usa service_role.

begin;

-- Soporte POS/anulacion por si supabase/schema_pos.sql aun no se ejecuto.
alter table public.ventas
add column if not exists estado text not null default 'confirmada',
add column if not exists anulada_at timestamptz,
add column if not exists anulada_por text,
add column if not exists motivo_anulacion text;

alter table public.facturas
add column if not exists estado text not null default 'emitida',
add column if not exists venta_estado text,
add column if not exists anulada_at timestamptz;

create table if not exists public.contadores_recibos (
    id bigint generated by default as identity primary key,
    gimnasio_id bigint references public.gimnasios(id) on delete cascade,
    tipo text not null,
    ultimo_numero bigint not null default 0,
    updated_at timestamptz not null default now()
);

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'contadores_recibos_gimnasio_tipo_unique') then
        alter table public.contadores_recibos
        add constraint contadores_recibos_gimnasio_tipo_unique unique (gimnasio_id, tipo);
    end if;
end $$;

alter table public.movimientos_inventario
drop constraint if exists movimientos_inventario_tipo_check;

alter table public.movimientos_inventario
add constraint movimientos_inventario_tipo_check
check (tipo in ('entrada', 'salida', 'ajuste', 'anulacion')) not valid;

create index if not exists idx_ventas_gimnasio_estado_fecha
on public.ventas(gimnasio_id, estado, fecha desc);

create or replace function public.confirmar_venta_pos(
    p_items jsonb,
    p_metodo_pago text,
    p_referencia_pago text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_user_id uuid := auth.uid();
    v_perfil record;
    v_gimnasio_id bigint;
    v_numero_recibo text;
    v_ultimo bigint;
    v_venta_id bigint;
    v_factura_id bigint;
    v_total numeric(12,2) := 0;
    v_item record;
    v_producto public.productos%rowtype;
begin
    if v_user_id is null then
        raise exception 'Usuario no autenticado';
    end if;

    select id, gimnasio_id, rol, estado
    into v_perfil
    from public.perfiles
    where user_id = v_user_id
      and lower(coalesce(estado, '')) = 'activo'
    limit 1;

    if not found or v_perfil.gimnasio_id is null then
        raise exception 'Perfil no valido';
    end if;

    if v_perfil.rol not in ('administrador', 'recepcion') then
        raise exception 'Sin permiso para vender';
    end if;

    v_gimnasio_id := v_perfil.gimnasio_id;

    if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
        raise exception 'El carrito esta vacio';
    end if;

    if p_metodo_pago not in ('Efectivo', 'Tarjeta', 'Transferencia') then
        raise exception 'Metodo de pago invalido';
    end if;

    if p_metodo_pago in ('Tarjeta', 'Transferencia') and nullif(trim(coalesce(p_referencia_pago, '')), '') is null then
        raise exception 'La referencia es obligatoria para tarjeta o transferencia';
    end if;

    for v_item in
        select producto_id, sum(cantidad)::int4 as cantidad
        from jsonb_to_recordset(p_items) as item(producto_id bigint, cantidad int4)
        group by producto_id
        order by producto_id
    loop
        if v_item.producto_id is null then
            raise exception 'Producto invalido en el carrito';
        end if;

        if v_item.cantidad is null or v_item.cantidad <= 0 then
            raise exception 'Cantidad invalida para producto %', v_item.producto_id;
        end if;

        select *
        into v_producto
        from public.productos
        where id = v_item.producto_id
        for update;

        if not found then
            raise exception 'Producto no pertenece al gimnasio';
        end if;

        if v_producto.gimnasio_id <> v_gimnasio_id then
            raise exception 'Producto no pertenece al gimnasio';
        end if;

        if lower(coalesce(v_producto.estado, '')) <> 'activo' then
            raise exception 'Producto inactivo: %', v_producto.nombre;
        end if;

        if v_producto.stock < v_item.cantidad then
            raise exception 'Stock insuficiente para %', v_producto.nombre;
        end if;

        v_total := v_total + (v_producto.precio * v_item.cantidad);
    end loop;

    if v_total <= 0 then
        raise exception 'Total de venta invalido';
    end if;

    insert into public.contadores_recibos (gimnasio_id, tipo, ultimo_numero)
    values (v_gimnasio_id, 'venta', 1)
    on conflict (gimnasio_id, tipo)
    do update set
        ultimo_numero = public.contadores_recibos.ultimo_numero + 1,
        updated_at = now()
    returning ultimo_numero into v_ultimo;

    v_numero_recibo := 'VEN-' || lpad(v_ultimo::text, 6, '0');

    insert into public.ventas (
        gimnasio_id, fecha, metodo_pago, referencia_pago, total,
        numero_recibo, usuario_registro, estado
    )
    values (
        v_gimnasio_id, current_date, p_metodo_pago,
        nullif(trim(coalesce(p_referencia_pago, '')), ''),
        v_total, v_numero_recibo, v_user_id::text, 'confirmada'
    )
    returning id into v_venta_id;

    for v_item in
        select producto_id, sum(cantidad)::int4 as cantidad
        from jsonb_to_recordset(p_items) as item(producto_id bigint, cantidad int4)
        group by producto_id
        order by producto_id
    loop
        select *
        into v_producto
        from public.productos
        where id = v_item.producto_id
          and gimnasio_id = v_gimnasio_id
        for update;

        if not found then
            raise exception 'Producto no pertenece al gimnasio';
        end if;

        if v_producto.stock < v_item.cantidad then
            raise exception 'Stock insuficiente para %', v_producto.nombre;
        end if;

        insert into public.venta_detalles (
            gimnasio_id, venta_id, producto_id, cantidad, precio_unitario, costo_unitario
        )
        values (
            v_gimnasio_id, v_venta_id, v_producto.id, v_item.cantidad,
            v_producto.precio, coalesce(v_producto.costo, 0)
        );

        update public.productos
        set stock = stock - v_item.cantidad,
            updated_at = now()
        where id = v_producto.id
          and gimnasio_id = v_gimnasio_id;

        insert into public.movimientos_inventario (
            gimnasio_id, producto_id, tipo, cantidad, stock_posterior,
            referencia_tipo, referencia_id, observacion, usuario_registro
        )
        values (
            v_gimnasio_id, v_producto.id, 'salida', v_item.cantidad,
            v_producto.stock - v_item.cantidad, 'venta', v_venta_id,
            'Venta POS ' || v_numero_recibo, v_user_id::text
        );
    end loop;

    insert into public.facturas (
        gimnasio_id, tipo, referencia_id, numero_recibo, fecha, cliente,
        concepto, metodo_pago, referencia_pago, total, usuario_registro,
        estado, venta_estado
    )
    values (
        v_gimnasio_id, 'venta_producto', v_venta_id, v_numero_recibo, current_date,
        'Cliente mostrador', 'venta de productos', p_metodo_pago,
        nullif(trim(coalesce(p_referencia_pago, '')), ''), v_total, v_user_id::text,
        'emitida', 'confirmada'
    )
    returning id into v_factura_id;

    return jsonb_build_object(
        'venta_id', v_venta_id,
        'factura_id', v_factura_id,
        'numero_recibo', v_numero_recibo,
        'total', v_total
    );
end;
$$;

revoke execute on function public.confirmar_venta_pos(jsonb, text, text) from public, anon;
grant execute on function public.confirmar_venta_pos(jsonb, text, text) to authenticated;

commit;
