-- Kilvio FIT - schema seguro para base Supabase existente
-- Base actual compatible:
--   public."Miembros" con id bigint identity
--   public.pagos con id bigint identity y miembro_id bigint
--
-- IMPORTANTE:
-- - No usa DROP TABLE.
-- - No usa DELETE.
-- - No renombra public."Miembros".
-- - No convierte ids existentes a uuid.
-- - Ejecutar completo en Supabase SQL Editor y revisar cualquier NOTICE.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create table if not exists public.gimnasios (
    id bigint generated by default as identity primary key,
    nombre text not null,
    telefono text,
    email text,
    direccion text,
    logo_url text,
    estado text not null default 'activo',
    plan text not null default 'basico',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public."Miembros" add column if not exists gimnasio_id bigint;
alter table public."Miembros" add column if not exists updated_at timestamptz default now();

alter table public.pagos add column if not exists gimnasio_id bigint;
alter table public.pagos add column if not exists updated_at timestamptz default now();

create table if not exists public.perfiles (
    id bigint generated by default as identity primary key,
    user_id uuid unique references auth.users(id) on delete cascade,
    gimnasio_id bigint references public.gimnasios(id) on delete restrict,
    nombre text not null,
    telefono text,
    rol text not null default 'recepcion',
    estado text not null default 'activo',
    permisos jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.asistencias (
    id bigint generated by default as identity primary key,
    gimnasio_id bigint references public.gimnasios(id) on delete cascade,
    miembro_id bigint references public."Miembros"(id) on delete cascade,
    fecha date not null default current_date,
    hora_llegada time not null default localtime,
    estado text not null default 'Presente',
    usuario_registro text,
    created_at timestamptz not null default now()
);

create table if not exists public.ingresos_diarios (
    id bigint generated by default as identity primary key,
    gimnasio_id bigint references public.gimnasios(id) on delete cascade,
    fecha date not null default current_date,
    cantidad int4 not null default 1,
    precio_unitario numeric(12,2) not null default 0,
    total numeric(12,2) generated always as (cantidad * precio_unitario) stored,
    usuario_registro text,
    created_at timestamptz not null default now()
);

create table if not exists public.productos (
    id bigint generated by default as identity primary key,
    gimnasio_id bigint references public.gimnasios(id) on delete cascade,
    nombre text not null,
    categoria text not null default 'Otros',
    precio numeric(12,2) not null default 0,
    costo numeric(12,2) not null default 0,
    stock int4 not null default 0,
    stock_minimo int4 not null default 0,
    imagen_url text,
    estado text not null default 'activo',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.proveedores (
    id bigint generated by default as identity primary key,
    gimnasio_id bigint references public.gimnasios(id) on delete cascade,
    nombre text not null,
    telefono text,
    email text,
    direccion text,
    producto_principal text,
    observaciones text,
    estado text not null default 'activo',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.compras_proveedores (
    id bigint generated by default as identity primary key,
    gimnasio_id bigint references public.gimnasios(id) on delete cascade,
    proveedor_id bigint references public.proveedores(id) on delete set null,
    producto_id bigint references public.productos(id) on delete restrict,
    cantidad int4 not null,
    costo_unitario numeric(12,2) not null,
    total numeric(12,2) generated always as (cantidad * costo_unitario) stored,
    fecha date not null default current_date,
    observacion text,
    usuario_registro text,
    created_at timestamptz not null default now()
);

create table if not exists public.ventas (
    id bigint generated by default as identity primary key,
    gimnasio_id bigint references public.gimnasios(id) on delete cascade,
    fecha date not null default current_date,
    metodo_pago text not null default 'Efectivo',
    referencia_pago text,
    total numeric(12,2) not null default 0,
    numero_recibo text,
    usuario_registro text,
    created_at timestamptz not null default now()
);

create table if not exists public.venta_detalles (
    id bigint generated by default as identity primary key,
    gimnasio_id bigint references public.gimnasios(id) on delete cascade,
    venta_id bigint references public.ventas(id) on delete cascade,
    producto_id bigint references public.productos(id) on delete restrict,
    cantidad int4 not null,
    precio_unitario numeric(12,2) not null,
    costo_unitario numeric(12,2) not null default 0,
    total numeric(12,2) generated always as (cantidad * precio_unitario) stored,
    created_at timestamptz not null default now()
);

create table if not exists public.movimientos_inventario (
    id bigint generated by default as identity primary key,
    gimnasio_id bigint references public.gimnasios(id) on delete cascade,
    producto_id bigint references public.productos(id) on delete restrict,
    tipo text not null,
    cantidad int4 not null,
    stock_posterior int4 not null,
    referencia_tipo text,
    referencia_id bigint,
    observacion text,
    usuario_registro text,
    created_at timestamptz not null default now()
);

create table if not exists public.configuracion_mensualidad (
    id bigint generated by default as identity primary key,
    gimnasio_id bigint references public.gimnasios(id) on delete cascade,
    monto_mensual numeric(12,2) not null default 750,
    entrada_diaria numeric(12,2) not null default 40,
    dias_prorroga int2 not null default 3,
    estado text not null default 'Activo',
    nota text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.facturas (
    id bigint generated by default as identity primary key,
    gimnasio_id bigint references public.gimnasios(id) on delete cascade,
    tipo text not null,
    referencia_id bigint not null,
    numero_recibo text not null,
    fecha date not null default current_date,
    cliente text,
    concepto text not null,
    metodo_pago text,
    referencia_pago text,
    total numeric(12,2) not null default 0,
    usuario_registro text,
    created_at timestamptz not null default now()
);

create table if not exists public.notificaciones (
    id bigint generated by default as identity primary key,
    gimnasio_id bigint references public.gimnasios(id) on delete cascade,
    miembro_id bigint references public."Miembros"(id) on delete cascade,
    tipo text not null,
    canal text not null,
    mensaje text not null,
    estado text not null default 'pendiente',
    fecha_programada timestamptz,
    fecha_enviada timestamptz,
    created_at timestamptz not null default now()
);

create table if not exists public.contadores_recibos (
    id bigint generated by default as identity primary key,
    gimnasio_id bigint references public.gimnasios(id) on delete cascade,
    tipo text not null,
    ultimo_numero bigint not null default 0,
    updated_at timestamptz not null default now()
);

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'miembros_gimnasio_fk') then
        alter table public."Miembros"
        add constraint miembros_gimnasio_fk
        foreign key (gimnasio_id) references public.gimnasios(id) on delete restrict not valid;
    end if;

    if not exists (select 1 from pg_constraint where conname = 'pagos_miembro_fk') then
        alter table public.pagos
        add constraint pagos_miembro_fk
        foreign key (miembro_id) references public."Miembros"(id) on delete restrict not valid;
    end if;

    if not exists (select 1 from pg_constraint where conname = 'pagos_gimnasio_fk') then
        alter table public.pagos
        add constraint pagos_gimnasio_fk
        foreign key (gimnasio_id) references public.gimnasios(id) on delete restrict not valid;
    end if;

    if not exists (select 1 from pg_constraint where conname = 'asistencias_miembro_fecha_unique') then
        alter table public.asistencias
        add constraint asistencias_miembro_fecha_unique unique (gimnasio_id, miembro_id, fecha);
    end if;

    if not exists (select 1 from pg_constraint where conname = 'configuracion_mensualidad_gimnasio_unique') then
        alter table public.configuracion_mensualidad
        add constraint configuracion_mensualidad_gimnasio_unique unique (gimnasio_id);
    end if;

    if not exists (select 1 from pg_constraint where conname = 'contadores_recibos_gimnasio_tipo_unique') then
        alter table public.contadores_recibos
        add constraint contadores_recibos_gimnasio_tipo_unique unique (gimnasio_id, tipo);
    end if;

    if not exists (select 1 from pg_constraint where conname = 'facturas_numero_gimnasio_unique') then
        alter table public.facturas
        add constraint facturas_numero_gimnasio_unique unique (gimnasio_id, numero_recibo);
    end if;

    if not exists (select 1 from pg_constraint where conname = 'facturas_referencia_unique') then
        alter table public.facturas
        add constraint facturas_referencia_unique unique (gimnasio_id, tipo, referencia_id);
    end if;

    if not exists (select 1 from pg_constraint where conname = 'productos_stock_check') then
        alter table public.productos add constraint productos_stock_check check (stock >= 0) not valid;
    end if;
end $$;

create index if not exists idx_miembros_gimnasio_estado on public."Miembros"(gimnasio_id, estado);
create index if not exists idx_miembros_cedula on public."Miembros"(cedula);
create index if not exists idx_pagos_gimnasio_fecha on public.pagos(gimnasio_id, fecha_pago desc);
create index if not exists idx_pagos_miembro_mes on public.pagos(miembro_id, mes);
create index if not exists idx_asistencias_gimnasio_fecha on public.asistencias(gimnasio_id, fecha desc);
create index if not exists idx_productos_gimnasio_estado on public.productos(gimnasio_id, estado);
create index if not exists idx_proveedores_gimnasio_estado on public.proveedores(gimnasio_id, estado);
create index if not exists idx_compras_gimnasio_fecha on public.compras_proveedores(gimnasio_id, fecha desc);
create index if not exists idx_ventas_gimnasio_fecha on public.ventas(gimnasio_id, fecha desc);
create index if not exists idx_venta_detalles_venta on public.venta_detalles(venta_id);
create index if not exists idx_movimientos_gimnasio_producto on public.movimientos_inventario(gimnasio_id, producto_id, created_at desc);
create index if not exists idx_facturas_gimnasio_fecha on public.facturas(gimnasio_id, fecha desc);
create index if not exists idx_notificaciones_gimnasio_estado on public.notificaciones(gimnasio_id, estado, fecha_programada);

do $$
begin
    if not exists (select 1 from pg_trigger where tgname = 'set_gimnasios_updated_at') then
        create trigger set_gimnasios_updated_at
        before update on public.gimnasios
        for each row execute function public.set_updated_at();
    end if;

    if not exists (select 1 from pg_trigger where tgname = 'set_miembros_updated_at') then
        create trigger set_miembros_updated_at
        before update on public."Miembros"
        for each row execute function public.set_updated_at();
    end if;

    if not exists (select 1 from pg_trigger where tgname = 'set_pagos_updated_at') then
        create trigger set_pagos_updated_at
        before update on public.pagos
        for each row execute function public.set_updated_at();
    end if;

    if not exists (select 1 from pg_trigger where tgname = 'set_perfiles_updated_at') then
        create trigger set_perfiles_updated_at
        before update on public.perfiles
        for each row execute function public.set_updated_at();
    end if;

    if not exists (select 1 from pg_trigger where tgname = 'set_productos_updated_at') then
        create trigger set_productos_updated_at
        before update on public.productos
        for each row execute function public.set_updated_at();
    end if;

    if not exists (select 1 from pg_trigger where tgname = 'set_proveedores_updated_at') then
        create trigger set_proveedores_updated_at
        before update on public.proveedores
        for each row execute function public.set_updated_at();
    end if;

    if not exists (select 1 from pg_trigger where tgname = 'set_configuracion_mensualidad_updated_at') then
        create trigger set_configuracion_mensualidad_updated_at
        before update on public.configuracion_mensualidad
        for each row execute function public.set_updated_at();
    end if;
end $$;

insert into public.gimnasios (nombre, telefono, email, direccion)
select 'Kilvio FIT', '809-000-0000', 'admin@kilviofit.com', 'Direccion pendiente'
where not exists (select 1 from public.gimnasios where lower(nombre) = lower('Kilvio FIT'));

update public."Miembros"
set gimnasio_id = (select id from public.gimnasios where lower(nombre) = lower('Kilvio FIT') order by id limit 1)
where gimnasio_id is null;

update public.pagos
set gimnasio_id = coalesce(
    (select m.gimnasio_id from public."Miembros" m where m.id = pagos.miembro_id),
    (select id from public.gimnasios where lower(nombre) = lower('Kilvio FIT') order by id limit 1)
)
where gimnasio_id is null;

insert into public.configuracion_mensualidad (gimnasio_id, monto_mensual, entrada_diaria, dias_prorroga, estado)
select g.id, 750, 40, 3, 'Activo'
from public.gimnasios g
where lower(g.nombre) = lower('Kilvio FIT')
  and not exists (
      select 1 from public.configuracion_mensualidad cm where cm.gimnasio_id = g.id
  );

insert into public.productos (gimnasio_id, nombre, categoria, precio, costo, stock, stock_minimo, estado)
select g.id, producto.nombre, producto.categoria, producto.precio, producto.costo, producto.stock, producto.stock_minimo, 'activo'
from public.gimnasios g
cross join (
    values
        ('Agua 500ml', 'Bebidas', 35::numeric, 20::numeric, 0::int4, 5::int4),
        ('Agua 1 litro', 'Bebidas', 50::numeric, 30::numeric, 0::int4, 5::int4),
        ('Gatorade Azul', 'Bebidas', 75::numeric, 48::numeric, 0::int4, 5::int4),
        ('Gatorade Naranja', 'Bebidas', 75::numeric, 48::numeric, 0::int4, 5::int4),
        ('Gatorade Fruit Punch', 'Bebidas', 75::numeric, 48::numeric, 0::int4, 5::int4),
        ('Powerade Azul', 'Bebidas', 70::numeric, 45::numeric, 0::int4, 5::int4),
        ('Powerade Rojo', 'Bebidas', 70::numeric, 45::numeric, 0::int4, 5::int4),
        ('Red Bull', 'Bebidas', 125::numeric, 85::numeric, 0::int4, 5::int4),
        ('Bolon', 'Snacks', 60::numeric, 35::numeric, 0::int4, 5::int4),
        ('Paleta de Chocolate', 'Snacks', 45::numeric, 25::numeric, 0::int4, 5::int4),
        ('Paleta de Leche', 'Snacks', 45::numeric, 25::numeric, 0::int4, 5::int4),
        ('Barra de Proteina', 'Snacks', 120::numeric, 80::numeric, 0::int4, 5::int4),
        ('Mani', 'Snacks', 40::numeric, 22::numeric, 0::int4, 5::int4),
        ('Granola', 'Snacks', 55::numeric, 32::numeric, 0::int4, 5::int4),
        ('Galletas Fitness', 'Snacks', 65::numeric, 38::numeric, 0::int4, 5::int4),
        ('Proteina Whey 1 lb', 'Suplementos', 1200::numeric, 780::numeric, 0::int4, 2::int4),
        ('Proteina Whey 5 lb', 'Suplementos', 2500::numeric, 1700::numeric, 0::int4, 2::int4),
        ('Creatina Monohidratada', 'Suplementos', 1200::numeric, 780::numeric, 0::int4, 2::int4),
        ('BCAA', 'Suplementos', 950::numeric, 600::numeric, 0::int4, 2::int4),
        ('Pre Workout', 'Suplementos', 1400::numeric, 900::numeric, 0::int4, 2::int4),
        ('Omega 3', 'Suplementos', 950::numeric, 610::numeric, 0::int4, 2::int4),
        ('Multivitaminico', 'Suplementos', 800::numeric, 500::numeric, 0::int4, 2::int4),
        ('L-Carnitina', 'Suplementos', 1100::numeric, 700::numeric, 0::int4, 2::int4),
        ('Guantes', 'Accesorios', 650::numeric, 420::numeric, 0::int4, 3::int4),
        ('Muñequeras', 'Accesorios', 350::numeric, 210::numeric, 0::int4, 3::int4),
        ('Botellas Deportivas', 'Accesorios', 300::numeric, 180::numeric, 0::int4, 3::int4),
        ('Toallas', 'Accesorios', 250::numeric, 140::numeric, 0::int4, 3::int4),
        ('Bandas Elasticas', 'Accesorios', 450::numeric, 280::numeric, 0::int4, 3::int4)
) as producto(nombre, categoria, precio, costo, stock, stock_minimo)
where lower(g.nombre) = lower('Kilvio FIT')
  and not exists (
      select 1
      from public.productos p
      where p.gimnasio_id = g.id
        and lower(p.nombre) = lower(producto.nombre)
  );

create or replace function public.current_gimnasio_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
    select gimnasio_id
    from public.perfiles
    where user_id = auth.uid()
      and estado = 'activo'
    limit 1;
$$;

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
    select rol
    from public.perfiles
    where user_id = auth.uid()
      and estado = 'activo'
    limit 1;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(public.current_user_role() = 'administrador', false);
$$;

create or replace function public.generar_numero_recibo(p_tipo text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
    v_gimnasio_id bigint := public.current_gimnasio_id();
    v_ultimo bigint;
    v_prefijo text;
begin
    if auth.uid() is null then
        raise exception 'Usuario no autenticado';
    end if;

    if v_gimnasio_id is null then
        raise exception 'Perfil sin gimnasio activo';
    end if;

    if p_tipo not in ('pago', 'venta', 'factura') then
        raise exception 'Tipo de recibo invalido';
    end if;

    insert into public.contadores_recibos (gimnasio_id, tipo, ultimo_numero)
    values (v_gimnasio_id, p_tipo, 1)
    on conflict (gimnasio_id, tipo)
    do update set
        ultimo_numero = public.contadores_recibos.ultimo_numero + 1,
        updated_at = now()
    returning ultimo_numero into v_ultimo;

    v_prefijo := case p_tipo
        when 'pago' then 'PAG'
        when 'venta' then 'VEN'
        else 'FAC'
    end;

    return v_prefijo || '-' || lpad(v_ultimo::text, 6, '0');
end;
$$;

create or replace function public.registrar_pago(
    p_miembro_id bigint,
    p_mes text,
    p_fecha_pago date default current_date,
    p_metodo_pago text default 'Efectivo',
    p_referencia_pago text default null
)
returns table (
    pago_id bigint,
    factura_id bigint,
    numero_recibo text,
    monto numeric,
    miembro_nombre text
)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_gimnasio_id bigint := public.current_gimnasio_id();
    v_miembro public."Miembros"%rowtype;
    v_monto numeric(12,2);
    v_pago_id bigint;
    v_factura_id bigint;
    v_numero text;
begin
    if auth.uid() is null then
        raise exception 'Usuario no autenticado';
    end if;

    if v_gimnasio_id is null then
        raise exception 'Perfil sin gimnasio activo';
    end if;

    if p_metodo_pago not in ('Efectivo', 'Tarjeta', 'Transferencia') then
        raise exception 'Metodo de pago invalido';
    end if;

    if p_metodo_pago in ('Tarjeta', 'Transferencia') and nullif(trim(coalesce(p_referencia_pago, '')), '') is null then
        raise exception 'La referencia es obligatoria para tarjeta o transferencia';
    end if;

    select * into v_miembro
    from public."Miembros"
    where id = p_miembro_id
      and gimnasio_id = v_gimnasio_id
      and coalesce(estado, 'activo') = 'activo'
    for update;

    if not found then
        raise exception 'Miembro no encontrado o inactivo';
    end if;

    select coalesce(nullif(v_miembro.monto_mensual, 0), cm.monto_mensual)
    into v_monto
    from public.configuracion_mensualidad cm
    where cm.gimnasio_id = v_gimnasio_id
    limit 1;

    v_monto := coalesce(nullif(v_monto, 0), v_miembro.monto_mensual);

    if v_monto is null or v_monto <= 0 then
        raise exception 'Monto de mensualidad no configurado';
    end if;

    v_numero := public.generar_numero_recibo('pago');

    insert into public.pagos (
        miembro_id, gimnasio_id, monto, mes, fecha_pago, metodo_pago,
        referencia_pago, estado, concepto, numero_recibo, usuario_registro
    )
    values (
        p_miembro_id, v_gimnasio_id, v_monto, p_mes, coalesce(p_fecha_pago, current_date),
        p_metodo_pago, nullif(trim(coalesce(p_referencia_pago, '')), ''),
        'Pagado', 'mensualidad', v_numero, auth.uid()::text
    )
    returning id into v_pago_id;

    insert into public.facturas (
        gimnasio_id, tipo, referencia_id, numero_recibo, fecha, cliente,
        concepto, metodo_pago, referencia_pago, total, usuario_registro
    )
    values (
        v_gimnasio_id, 'mensualidad', v_pago_id, v_numero,
        coalesce(p_fecha_pago, current_date), v_miembro.nombre,
        'mensualidad', p_metodo_pago,
        nullif(trim(coalesce(p_referencia_pago, '')), ''), v_monto, auth.uid()::text
    )
    returning id into v_factura_id;

    return query select v_pago_id, v_factura_id, v_numero, v_monto, v_miembro.nombre;
end;
$$;

create or replace function public.vender_producto(
    p_producto_id bigint,
    p_cantidad int4 default 1,
    p_metodo_pago text default 'Efectivo',
    p_referencia_pago text default null
)
returns table (
    venta_id bigint,
    factura_id bigint,
    numero_recibo text,
    total numeric,
    stock_posterior int4
)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_gimnasio_id bigint := public.current_gimnasio_id();
    v_producto public.productos%rowtype;
    v_venta_id bigint;
    v_factura_id bigint;
    v_numero text;
    v_total numeric(12,2);
begin
    if auth.uid() is null then
        raise exception 'Usuario no autenticado';
    end if;

    if v_gimnasio_id is null then
        raise exception 'Perfil sin gimnasio activo';
    end if;

    if p_cantidad is null or p_cantidad <= 0 then
        raise exception 'Cantidad invalida';
    end if;

    if p_metodo_pago not in ('Efectivo', 'Tarjeta', 'Transferencia') then
        raise exception 'Metodo de pago invalido';
    end if;

    if p_metodo_pago in ('Tarjeta', 'Transferencia') and nullif(trim(coalesce(p_referencia_pago, '')), '') is null then
        raise exception 'La referencia es obligatoria para tarjeta o transferencia';
    end if;

    select * into v_producto
    from public.productos
    where id = p_producto_id
      and gimnasio_id = v_gimnasio_id
      and estado = 'activo'
    for update;

    if not found then
        raise exception 'Producto no encontrado o inactivo';
    end if;

    if v_producto.stock < p_cantidad then
        raise exception 'Stock insuficiente';
    end if;

    v_total := v_producto.precio * p_cantidad;
    v_numero := public.generar_numero_recibo('venta');

    update public.productos
    set stock = stock - p_cantidad,
        updated_at = now()
    where id = v_producto.id;

    insert into public.ventas (
        gimnasio_id, fecha, metodo_pago, referencia_pago,
        total, numero_recibo, usuario_registro
    )
    values (
        v_gimnasio_id, current_date, p_metodo_pago,
        nullif(trim(coalesce(p_referencia_pago, '')), ''),
        v_total, v_numero, auth.uid()::text
    )
    returning id into v_venta_id;

    insert into public.venta_detalles (
        gimnasio_id, venta_id, producto_id, cantidad, precio_unitario, costo_unitario
    )
    values (
        v_gimnasio_id, v_venta_id, v_producto.id, p_cantidad,
        v_producto.precio, v_producto.costo
    );

    insert into public.movimientos_inventario (
        gimnasio_id, producto_id, tipo, cantidad, stock_posterior,
        referencia_tipo, referencia_id, observacion, usuario_registro
    )
    values (
        v_gimnasio_id, v_producto.id, 'salida', p_cantidad,
        v_producto.stock - p_cantidad, 'venta', v_venta_id,
        p_metodo_pago, auth.uid()::text
    );

    insert into public.facturas (
        gimnasio_id, tipo, referencia_id, numero_recibo, fecha, cliente,
        concepto, metodo_pago, referencia_pago, total, usuario_registro
    )
    values (
        v_gimnasio_id, 'venta_producto', v_venta_id, v_numero, current_date,
        'Cliente mostrador', 'venta de productos', p_metodo_pago,
        nullif(trim(coalesce(p_referencia_pago, '')), ''), v_total, auth.uid()::text
    )
    returning id into v_factura_id;

    return query select v_venta_id, v_factura_id, v_numero, v_total, v_producto.stock - p_cantidad;
end;
$$;

create or replace function public.actualizar_stock(
    p_producto_id bigint,
    p_cantidad int4,
    p_costo_unitario numeric,
    p_proveedor_id bigint,
    p_fecha date default current_date,
    p_observacion text default null
)
returns table (
    compra_id bigint,
    stock_posterior int4,
    total numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_gimnasio_id bigint := public.current_gimnasio_id();
    v_producto public.productos%rowtype;
    v_proveedor public.proveedores%rowtype;
    v_compra_id bigint;
    v_total numeric(12,2);
begin
    if auth.uid() is null then
        raise exception 'Usuario no autenticado';
    end if;

    if v_gimnasio_id is null then
        raise exception 'Perfil sin gimnasio activo';
    end if;

    if not public.is_admin() then
        raise exception 'Solo administradores pueden actualizar stock';
    end if;

    if p_cantidad is null or p_cantidad <= 0 then
        raise exception 'Cantidad invalida';
    end if;

    if p_costo_unitario is null or p_costo_unitario < 0 then
        raise exception 'Costo unitario invalido';
    end if;

    select * into v_producto
    from public.productos
    where id = p_producto_id
      and gimnasio_id = v_gimnasio_id
    for update;

    if not found then
        raise exception 'Producto no encontrado';
    end if;

    select * into v_proveedor
    from public.proveedores
    where id = p_proveedor_id
      and gimnasio_id = v_gimnasio_id
      and estado = 'activo';

    if not found then
        raise exception 'Proveedor no encontrado o inactivo';
    end if;

    v_total := p_cantidad * p_costo_unitario;

    update public.productos
    set stock = stock + p_cantidad,
        costo = p_costo_unitario,
        updated_at = now()
    where id = v_producto.id;

    insert into public.compras_proveedores (
        gimnasio_id, proveedor_id, producto_id, cantidad, costo_unitario,
        fecha, observacion, usuario_registro
    )
    values (
        v_gimnasio_id, p_proveedor_id, p_producto_id, p_cantidad, p_costo_unitario,
        coalesce(p_fecha, current_date), p_observacion, auth.uid()::text
    )
    returning id into v_compra_id;

    insert into public.movimientos_inventario (
        gimnasio_id, producto_id, tipo, cantidad, stock_posterior,
        referencia_tipo, referencia_id, observacion, usuario_registro
    )
    values (
        v_gimnasio_id, p_producto_id, 'entrada', p_cantidad,
        v_producto.stock + p_cantidad, 'compra_proveedor',
        v_compra_id, p_observacion, auth.uid()::text
    );

    return query select v_compra_id, v_producto.stock + p_cantidad, v_total;
end;
$$;

revoke execute on function public.generar_numero_recibo(text) from public, anon;
revoke execute on function public.registrar_pago(bigint, text, date, text, text) from public, anon;
revoke execute on function public.vender_producto(bigint, int4, text, text) from public, anon;
revoke execute on function public.actualizar_stock(bigint, int4, numeric, bigint, date, text) from public, anon;
grant execute on function public.registrar_pago(bigint, text, date, text, text) to authenticated;
grant execute on function public.vender_producto(bigint, int4, text, text) to authenticated;
grant execute on function public.actualizar_stock(bigint, int4, numeric, bigint, date, text) to authenticated;

alter table public.gimnasios enable row level security;
alter table public."Miembros" enable row level security;
alter table public.pagos enable row level security;
alter table public.perfiles enable row level security;
alter table public.asistencias enable row level security;
alter table public.ingresos_diarios enable row level security;
alter table public.productos enable row level security;
alter table public.proveedores enable row level security;
alter table public.compras_proveedores enable row level security;
alter table public.ventas enable row level security;
alter table public.venta_detalles enable row level security;
alter table public.movimientos_inventario enable row level security;
alter table public.configuracion_mensualidad enable row level security;
alter table public.facturas enable row level security;
alter table public.notificaciones enable row level security;
alter table public.contadores_recibos enable row level security;

do $$
begin
    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'gimnasios' and policyname = 'Gimnasios visibles por perfil') then
        create policy "Gimnasios visibles por perfil"
        on public.gimnasios for select
        to authenticated
        using (id = public.current_gimnasio_id());
    end if;

    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'perfiles' and policyname = 'Usuarios ven perfiles de su gimnasio') then
        create policy "Usuarios ven perfiles de su gimnasio"
        on public.perfiles for select
        to authenticated
        using (user_id = auth.uid() or gimnasio_id = public.current_gimnasio_id());
    end if;

    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'Miembros' and policyname = 'Miembros visibles por gimnasio') then
        create policy "Miembros visibles por gimnasio"
        on public."Miembros" for select
        to authenticated
        using (gimnasio_id = public.current_gimnasio_id());
    end if;

    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'Miembros' and policyname = 'Miembros administrados por gimnasio') then
        create policy "Miembros administrados por gimnasio"
        on public."Miembros" for insert
        to authenticated
        with check (gimnasio_id = public.current_gimnasio_id());
    end if;

    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'Miembros' and policyname = 'Miembros actualizados por gimnasio') then
        create policy "Miembros actualizados por gimnasio"
        on public."Miembros" for update
        to authenticated
        using (gimnasio_id = public.current_gimnasio_id())
        with check (gimnasio_id = public.current_gimnasio_id());
    end if;

    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'pagos' and policyname = 'Pagos visibles por gimnasio') then
        create policy "Pagos visibles por gimnasio"
        on public.pagos for select
        to authenticated
        using (gimnasio_id = public.current_gimnasio_id());
    end if;

    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'asistencias' and policyname = 'Asistencias por gimnasio') then
        create policy "Asistencias por gimnasio"
        on public.asistencias for all
        to authenticated
        using (gimnasio_id = public.current_gimnasio_id())
        with check (gimnasio_id = public.current_gimnasio_id());
    end if;

    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'productos' and policyname = 'Productos visibles por gimnasio') then
        create policy "Productos visibles por gimnasio"
        on public.productos for select
        to authenticated
        using (gimnasio_id = public.current_gimnasio_id());
    end if;

    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'proveedores' and policyname = 'Proveedores administrados por gimnasio') then
        create policy "Proveedores administrados por gimnasio"
        on public.proveedores for all
        to authenticated
        using (gimnasio_id = public.current_gimnasio_id() and public.is_admin())
        with check (gimnasio_id = public.current_gimnasio_id() and public.is_admin());
    end if;

    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'compras_proveedores' and policyname = 'Compras visibles por gimnasio') then
        create policy "Compras visibles por gimnasio"
        on public.compras_proveedores for select
        to authenticated
        using (gimnasio_id = public.current_gimnasio_id());
    end if;

    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'ventas' and policyname = 'Ventas visibles por gimnasio') then
        create policy "Ventas visibles por gimnasio"
        on public.ventas for select
        to authenticated
        using (gimnasio_id = public.current_gimnasio_id());
    end if;

    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'venta_detalles' and policyname = 'Detalles visibles por gimnasio') then
        create policy "Detalles visibles por gimnasio"
        on public.venta_detalles for select
        to authenticated
        using (gimnasio_id = public.current_gimnasio_id());
    end if;

    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'movimientos_inventario' and policyname = 'Movimientos visibles por gimnasio') then
        create policy "Movimientos visibles por gimnasio"
        on public.movimientos_inventario for select
        to authenticated
        using (gimnasio_id = public.current_gimnasio_id());
    end if;

    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'configuracion_mensualidad' and policyname = 'Configuracion visible por gimnasio') then
        create policy "Configuracion visible por gimnasio"
        on public.configuracion_mensualidad for select
        to authenticated
        using (gimnasio_id = public.current_gimnasio_id());
    end if;

    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'facturas' and policyname = 'Facturas visibles por gimnasio') then
        create policy "Facturas visibles por gimnasio"
        on public.facturas for select
        to authenticated
        using (gimnasio_id = public.current_gimnasio_id());
    end if;

    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'notificaciones' and policyname = 'Notificaciones por gimnasio') then
        create policy "Notificaciones por gimnasio"
        on public.notificaciones for select
        to authenticated
        using (gimnasio_id = public.current_gimnasio_id());
    end if;
end $$;

-- Pendiente manual despues de crear el primer usuario en Supabase Auth:
-- insert into public.perfiles (user_id, gimnasio_id, nombre, rol, permisos)
-- select
--   'AUTH_USER_UUID',
--   g.id,
--   'Administrador',
--   'administrador',
--   '["dashboard","miembros","asistencia","pagos","registrar_pago","inventario","pos","proveedores","reportes","mensualidad","configuracion"]'::jsonb
-- from public.gimnasios g
-- where lower(g.nombre) = lower('Kilvio FIT')
--   and not exists (select 1 from public.perfiles where user_id = 'AUTH_USER_UUID');
