-- Kilvio FIT - Modulo Cuadre de Caja por Turno
-- Ejecutar en Supabase SQL Editor.
-- No borra datos existentes.

create table if not exists public.cajas_turno (
    id bigint generated by default as identity primary key,
    gimnasio_id uuid not null references public.gimnasios(id),
    usuario_id uuid not null references auth.users(id),
    usuario_nombre text not null,
    fecha date not null default current_date,
    hora_apertura time not null default localtime,
    hora_cierre time,
    monto_inicial numeric(12,2) not null default 0 check (monto_inicial >= 0),
    total_efectivo numeric(12,2) not null default 0,
    total_tarjeta numeric(12,2) not null default 0,
    total_generado numeric(12,2) not null default 0,
    monto_entregado numeric(12,2),
    diferencia numeric(12,2),
    estado text not null default 'abierta' check (estado in ('abierta', 'cerrada')),
    observaciones text,
    created_at timestamptz not null default now()
);

comment on table public.cajas_turno is 'Turnos de caja por usuario para asociar pagos, ventas POS, facturas e ingresos diarios.';
comment on column public.cajas_turno.monto_inicial is 'Efectivo inicial entregado al iniciar el turno.';
comment on column public.cajas_turno.total_efectivo is 'Total cobrado en efectivo durante el turno, sin incluir monto inicial.';
comment on column public.cajas_turno.total_tarjeta is 'Total cobrado por tarjeta/transferencia durante el turno.';
comment on column public.cajas_turno.diferencia is 'Monto entregado menos efectivo esperado: monto_inicial + total_efectivo.';

create unique index if not exists idx_cajas_turno_usuario_abierta
on public.cajas_turno (usuario_id)
where estado = 'abierta';

create index if not exists idx_cajas_turno_gimnasio_fecha
on public.cajas_turno (gimnasio_id, fecha desc);

create index if not exists idx_cajas_turno_gimnasio_estado
on public.cajas_turno (gimnasio_id, estado);

alter table public.pagos add column if not exists caja_turno_id bigint references public.cajas_turno(id);
alter table public.facturas add column if not exists caja_turno_id bigint references public.cajas_turno(id);
alter table public.ventas add column if not exists caja_turno_id bigint references public.cajas_turno(id);
alter table public.ingresos_diarios add column if not exists caja_turno_id bigint references public.cajas_turno(id);
alter table public.movimientos_inventario add column if not exists caja_turno_id bigint references public.cajas_turno(id);

create index if not exists idx_pagos_caja_turno on public.pagos (caja_turno_id);
create index if not exists idx_facturas_caja_turno on public.facturas (caja_turno_id);
create index if not exists idx_ventas_caja_turno on public.ventas (caja_turno_id);
create index if not exists idx_ingresos_diarios_caja_turno on public.ingresos_diarios (caja_turno_id);
create index if not exists idx_movimientos_inventario_caja_turno on public.movimientos_inventario (caja_turno_id);

create or replace function public.kilvio_current_user_profile()
returns table (
    gimnasio_id uuid,
    rol text,
    nombre text
)
language sql
stable
security invoker
set search_path = public
as $$
    select p.gimnasio_id, lower(p.rol), coalesce(p.nombre, 'Usuario')
    from public.perfiles p
    where p.user_id = auth.uid()
      and lower(p.estado) = 'activo'
    limit 1
$$;

create or replace function public.kilvio_current_caja_turno_id()
returns bigint
language sql
stable
security invoker
set search_path = public
as $$
    select c.id
    from public.cajas_turno c
    where c.usuario_id = auth.uid()
      and c.estado = 'abierta'
    order by c.created_at desc
    limit 1
$$;

create or replace function public.set_caja_turno_id()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    if new.caja_turno_id is null then
        new.caja_turno_id := public.kilvio_current_caja_turno_id();
    end if;

    return new;
end;
$$;

drop trigger if exists trg_pagos_set_caja_turno on public.pagos;
create trigger trg_pagos_set_caja_turno
before insert on public.pagos
for each row execute function public.set_caja_turno_id();

drop trigger if exists trg_facturas_set_caja_turno on public.facturas;
create trigger trg_facturas_set_caja_turno
before insert on public.facturas
for each row execute function public.set_caja_turno_id();

drop trigger if exists trg_ventas_set_caja_turno on public.ventas;
create trigger trg_ventas_set_caja_turno
before insert on public.ventas
for each row execute function public.set_caja_turno_id();

drop trigger if exists trg_ingresos_diarios_set_caja_turno on public.ingresos_diarios;
create trigger trg_ingresos_diarios_set_caja_turno
before insert on public.ingresos_diarios
for each row execute function public.set_caja_turno_id();

drop trigger if exists trg_movimientos_inventario_set_caja_turno on public.movimientos_inventario;
create trigger trg_movimientos_inventario_set_caja_turno
before insert on public.movimientos_inventario
for each row execute function public.set_caja_turno_id();

create or replace function public.abrir_caja_turno(
    p_monto_inicial numeric default 0,
    p_observaciones text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_auth_uid uuid := auth.uid();
    v_perfil record;
    v_caja_id bigint;
begin
    if v_auth_uid is null then
        raise exception 'Usuario no autenticado';
    end if;

    select *
    into v_perfil
    from public.kilvio_current_user_profile()
    limit 1;

    if v_perfil.gimnasio_id is null then
        raise exception 'Perfil activo no valido';
    end if;

    if v_perfil.rol not in ('administrador', 'recepcion') then
        raise exception 'Sin permiso para abrir caja';
    end if;

    if coalesce(p_monto_inicial, 0) < 0 then
        raise exception 'El monto inicial no puede ser negativo';
    end if;

    if exists (
        select 1
        from public.cajas_turno c
        where c.usuario_id = v_auth_uid
          and c.estado = 'abierta'
    ) then
        raise exception 'Este usuario ya tiene una caja abierta';
    end if;

    insert into public.cajas_turno (
        gimnasio_id,
        usuario_id,
        usuario_nombre,
        fecha,
        hora_apertura,
        monto_inicial,
        estado,
        observaciones
    )
    values (
        v_perfil.gimnasio_id,
        v_auth_uid,
        v_perfil.nombre,
        current_date,
        localtime,
        coalesce(p_monto_inicial, 0),
        'abierta',
        p_observaciones
    )
    returning id into v_caja_id;

    return jsonb_build_object(
        'caja_id', v_caja_id,
        'estado', 'abierta',
        'mensaje', 'Caja abierta correctamente'
    );
end;
$$;

create or replace function public.cerrar_caja_turno(
    p_caja_id bigint,
    p_monto_entregado numeric,
    p_observaciones text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_auth_uid uuid := auth.uid();
    v_perfil record;
    v_caja public.cajas_turno%rowtype;
    v_mensualidades numeric(12,2) := 0;
    v_ventas_pos numeric(12,2) := 0;
    v_ingresos_diarios numeric(12,2) := 0;
    v_efectivo numeric(12,2) := 0;
    v_tarjeta numeric(12,2) := 0;
    v_total numeric(12,2) := 0;
    v_diferencia numeric(12,2) := 0;
begin
    if v_auth_uid is null then
        raise exception 'Usuario no autenticado';
    end if;

    if p_monto_entregado is null or p_monto_entregado < 0 then
        raise exception 'El monto entregado debe ser mayor o igual a cero';
    end if;

    select *
    into v_perfil
    from public.kilvio_current_user_profile()
    limit 1;

    if v_perfil.gimnasio_id is null then
        raise exception 'Perfil activo no valido';
    end if;

    if v_perfil.rol not in ('administrador', 'recepcion') then
        raise exception 'Sin permiso para cerrar caja';
    end if;

    select *
    into v_caja
    from public.cajas_turno c
    where c.id = p_caja_id
      and c.gimnasio_id = v_perfil.gimnasio_id
    for update;

    if not found then
        raise exception 'Caja no encontrada';
    end if;

    if v_caja.estado <> 'abierta' then
        raise exception 'La caja ya esta cerrada';
    end if;

    if v_caja.usuario_id <> v_auth_uid and v_perfil.rol <> 'administrador' then
        raise exception 'Solo puedes cerrar tu propia caja';
    end if;

    select coalesce(sum(monto), 0)
    into v_mensualidades
    from public.pagos
    where caja_turno_id = p_caja_id
      and lower(coalesce(estado, '')) = 'pagado';

    select coalesce(sum(total), 0)
    into v_ventas_pos
    from public.ventas
    where caja_turno_id = p_caja_id
      and lower(coalesce(estado, 'confirmada')) <> 'anulada';

    select coalesce(sum(total), 0)
    into v_ingresos_diarios
    from public.ingresos_diarios
    where caja_turno_id = p_caja_id;

    select coalesce(sum(monto), 0)
    into v_efectivo
    from public.pagos
    where caja_turno_id = p_caja_id
      and lower(coalesce(estado, '')) = 'pagado'
      and lower(coalesce(metodo_pago, '')) = 'efectivo';

    select v_efectivo + coalesce(sum(total), 0)
    into v_efectivo
    from public.ventas
    where caja_turno_id = p_caja_id
      and lower(coalesce(estado, 'confirmada')) <> 'anulada'
      and lower(coalesce(metodo_pago, '')) = 'efectivo';

    v_efectivo := v_efectivo + v_ingresos_diarios;

    select coalesce(sum(monto), 0)
    into v_tarjeta
    from public.pagos
    where caja_turno_id = p_caja_id
      and lower(coalesce(estado, '')) = 'pagado'
      and lower(coalesce(metodo_pago, '')) in ('tarjeta', 'transferencia');

    select v_tarjeta + coalesce(sum(total), 0)
    into v_tarjeta
    from public.ventas
    where caja_turno_id = p_caja_id
      and lower(coalesce(estado, 'confirmada')) <> 'anulada'
      and lower(coalesce(metodo_pago, '')) = 'tarjeta';

    v_total := v_mensualidades + v_ventas_pos + v_ingresos_diarios;
    v_diferencia := p_monto_entregado - (v_caja.monto_inicial + v_efectivo);

    update public.cajas_turno
    set
        hora_cierre = localtime,
        total_efectivo = v_efectivo,
        total_tarjeta = v_tarjeta,
        total_generado = v_total,
        monto_entregado = p_monto_entregado,
        diferencia = v_diferencia,
        estado = 'cerrada',
        observaciones = nullif(trim(concat_ws(E'\n', v_caja.observaciones, p_observaciones)), '')
    where id = p_caja_id;

    return jsonb_build_object(
        'caja_id', p_caja_id,
        'estado', 'cerrada',
        'total_efectivo', v_efectivo,
        'total_tarjeta', v_tarjeta,
        'total_generado', v_total,
        'monto_entregado', p_monto_entregado,
        'diferencia', v_diferencia,
        'resultado', case
            when v_diferencia = 0 then 'Cuadre correcto'
            when v_diferencia > 0 then 'Sobrante'
            else 'Faltante'
        end,
        'mensaje', 'Caja cerrada correctamente'
    );
end;
$$;

alter table public.cajas_turno enable row level security;

drop policy if exists "cajas_turno_select_gimnasio" on public.cajas_turno;
create policy "cajas_turno_select_gimnasio"
on public.cajas_turno
for select
to authenticated
using (
    exists (
        select 1
        from public.perfiles p
        where p.user_id = auth.uid()
          and lower(p.estado) = 'activo'
          and p.gimnasio_id = cajas_turno.gimnasio_id
          and (
              lower(p.rol) = 'administrador'
              or cajas_turno.usuario_id = auth.uid()
          )
    )
);

drop policy if exists "cajas_turno_insert_usuario" on public.cajas_turno;
create policy "cajas_turno_insert_usuario"
on public.cajas_turno
for insert
to authenticated
with check (
    usuario_id = auth.uid()
    and exists (
        select 1
        from public.perfiles p
        where p.user_id = auth.uid()
          and lower(p.estado) = 'activo'
          and p.gimnasio_id = cajas_turno.gimnasio_id
          and lower(p.rol) in ('administrador', 'recepcion')
    )
);

drop policy if exists "cajas_turno_update_usuario" on public.cajas_turno;
create policy "cajas_turno_update_usuario"
on public.cajas_turno
for update
to authenticated
using (
    exists (
        select 1
        from public.perfiles p
        where p.user_id = auth.uid()
          and lower(p.estado) = 'activo'
          and p.gimnasio_id = cajas_turno.gimnasio_id
          and lower(p.rol) in ('administrador', 'recepcion')
          and (lower(p.rol) = 'administrador' or cajas_turno.usuario_id = auth.uid())
    )
)
with check (
    exists (
        select 1
        from public.perfiles p
        where p.user_id = auth.uid()
          and lower(p.estado) = 'activo'
          and p.gimnasio_id = cajas_turno.gimnasio_id
          and lower(p.rol) in ('administrador', 'recepcion')
          and (lower(p.rol) = 'administrador' or cajas_turno.usuario_id = auth.uid())
    )
);

grant execute on function public.abrir_caja_turno(numeric, text) to authenticated;
grant execute on function public.cerrar_caja_turno(bigint, numeric, text) to authenticated;
grant execute on function public.kilvio_current_caja_turno_id() to authenticated;

notify pgrst, 'reload schema';
