-- 001_base_schema.sql
-- Base schema normalized for clean Supabase staging.
-- Standard: gimnasio_id is uuid. Canonical members table: public."Miembros".

create extension if not exists pgcrypto;
create schema if not exists app_private;

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.gimnasios (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  nombre_comercial text,
  rnc text,
  telefono text,
  email text,
  direccion text,
  estado text not null default 'activo' check (estado in ('activo','inactivo','suspendido')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public."Miembros" (
  id bigint generated by default as identity primary key,
  gimnasio_id uuid not null references public.gimnasios(id) on delete cascade,
  nombre text not null,
  cedula text,
  telefono text,
  email text,
  direccion text,
  fecha_nacimiento date,
  fecha_inscripcion date not null default current_date,
  estado text not null default 'activo' check (estado in ('activo','inactivo','suspendido','vencido')),
  membresia text,
  plan text,
  monto_mensual numeric(12,2) not null default 0,
  fecha_inicio date,
  fecha_vencimiento date,
  observaciones text,
  foto_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (gimnasio_id, cedula)
);

create table if not exists public.perfiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  gimnasio_id uuid references public.gimnasios(id) on delete restrict,
  nombre text,
  telefono text,
  rol text not null check (rol in ('administrador','recepcion','super_admin_saas')),
  estado text not null default 'activo' check (estado in ('activo','inactivo','suspendido')),
  permisos jsonb not null default '[]'::jsonb,
  ultimo_acceso timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint perfiles_super_admin_gimnasio_chk check (
    (rol = 'super_admin_saas' and gimnasio_id is null)
    or (rol <> 'super_admin_saas' and gimnasio_id is not null)
  )
);

create table if not exists public.solicitudes_acceso (
  id uuid primary key default gen_random_uuid(),
  gimnasio_id uuid not null references public.gimnasios(id) on delete cascade,
  email text not null,
  nombre text,
  rol text not null default 'recepcion' check (rol in ('administrador','recepcion')),
  estado text not null default 'pendiente' check (estado in ('pendiente','aprobada','rechazada','cancelada')),
  token text unique,
  solicitado_por uuid references auth.users(id) on delete set null,
  respondido_por uuid references auth.users(id) on delete set null,
  respondido_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pagos (
  id bigint generated by default as identity primary key,
  gimnasio_id uuid not null references public.gimnasios(id) on delete cascade,
  miembro_id bigint references public."Miembros"(id) on delete set null,
  monto numeric(12,2) not null check (monto >= 0),
  mes text,
  fecha_pago timestamptz not null default now(),
  metodo_pago text not null default 'efectivo',
  banco text,
  referencia_pago text,
  concepto text not null default 'mensualidad',
  estado text not null default 'pagado' check (estado in ('pendiente','pagado','anulado')),
  numero_recibo text,
  usuario_registro text,
  caja_turno_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.asistencias (
  id bigint generated by default as identity primary key,
  gimnasio_id uuid not null references public.gimnasios(id) on delete cascade,
  miembro_id bigint not null references public."Miembros"(id) on delete cascade,
  fecha timestamptz not null default now(),
  metodo text not null default 'manual',
  usuario_registro uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  gimnasio_id uuid not null references public.gimnasios(id) on delete cascade,
  nombre text not null,
  descripcion text,
  categoria text,
  sku text,
  precio numeric(12,2) not null default 0,
  costo numeric(12,2) not null default 0,
  stock integer not null default 0,
  stock_minimo integer not null default 0,
  activo boolean not null default true,
  imagen_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (gimnasio_id, sku)
);

create table if not exists public.proveedores (
  id bigint generated by default as identity primary key,
  gimnasio_id uuid not null references public.gimnasios(id) on delete cascade,
  nombre text not null,
  telefono text,
  email text,
  direccion text,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ventas (
  id bigint generated by default as identity primary key,
  gimnasio_id uuid not null references public.gimnasios(id) on delete cascade,
  miembro_id bigint references public."Miembros"(id) on delete set null,
  subtotal numeric(12,2) not null default 0,
  descuento numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  metodo_pago text not null default 'efectivo',
  banco text,
  referencia_pago text,
  monto_recibido numeric(12,2),
  cambio numeric(12,2),
  estado text not null default 'confirmada' check (estado in ('pendiente','confirmada','anulada')),
  numero_recibo text,
  caja_turno_id bigint,
  usuario_id uuid references auth.users(id) on delete set null,
  anulada_por uuid references auth.users(id) on delete set null,
  motivo_anulacion text,
  anulada_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.venta_detalles (
  id bigint generated by default as identity primary key,
  gimnasio_id uuid not null references public.gimnasios(id) on delete cascade,
  venta_id bigint not null references public.ventas(id) on delete cascade,
  producto_id bigint not null references public.productos(id) on delete restrict,
  producto_nombre text not null,
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(12,2) not null default 0,
  costo_unitario numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.movimientos_inventario (
  id bigint generated by default as identity primary key,
  gimnasio_id uuid not null references public.gimnasios(id) on delete cascade,
  producto_id bigint not null references public.productos(id) on delete cascade,
  tipo text not null check (tipo in ('entrada','salida','ajuste','anulacion')),
  cantidad integer not null,
  stock_anterior integer not null,
  stock_nuevo integer not null,
  referencia_tipo text,
  referencia_id bigint,
  motivo text,
  usuario_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.facturas (
  id bigint generated by default as identity primary key,
  gimnasio_id uuid not null references public.gimnasios(id) on delete cascade,
  venta_id bigint references public.ventas(id) on delete set null,
  pago_id bigint references public.pagos(id) on delete set null,
  numero text not null,
  tipo text not null default 'pos',
  cliente_nombre text,
  cliente_identificacion text,
  subtotal numeric(12,2) not null default 0,
  impuestos numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  estado text not null default 'emitida' check (estado in ('emitida','anulada')),
  fecha_emision timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (gimnasio_id, numero)
);

create table if not exists public.contadores_recibos (
  gimnasio_id uuid not null references public.gimnasios(id) on delete cascade,
  tipo text not null,
  ultimo_numero bigint not null default 0,
  updated_at timestamptz not null default now(),
  primary key (gimnasio_id, tipo)
);

create table if not exists public.cajas_turno (
  id bigint generated by default as identity primary key,
  gimnasio_id uuid not null references public.gimnasios(id) on delete cascade,
  usuario_id uuid not null references auth.users(id) on delete restrict,
  turno text not null check (turno in ('manana','tarde','noche')),
  fecha date not null default current_date,
  hora_inicio timestamptz not null default now(),
  hora_fin timestamptz,
  monto_inicial numeric(12,2) not null default 0,
  total_efectivo numeric(12,2) not null default 0,
  total_tarjeta numeric(12,2) not null default 0,
  total_transferencia numeric(12,2) not null default 0,
  total_sistema numeric(12,2) not null default 0,
  total_contado numeric(12,2),
  diferencia numeric(12,2),
  estado text not null default 'abierta' check (estado in ('abierta','pendiente_cuadre','cuadrada','reabierta')),
  observaciones text,
  hora_cuadre timestamptz,
  fecha_cuadre timestamptz,
  cuadrado_por uuid references auth.users(id) on delete set null,
  reabierta_por uuid references auth.users(id) on delete set null,
  motivo_reapertura text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (gimnasio_id, usuario_id, fecha, turno)
);

alter table public.pagos drop constraint if exists pagos_caja_turno_fk;
alter table public.pagos add constraint pagos_caja_turno_fk foreign key (caja_turno_id) references public.cajas_turno(id) on delete set null;
alter table public.ventas drop constraint if exists ventas_caja_turno_fk;
alter table public.ventas add constraint ventas_caja_turno_fk foreign key (caja_turno_id) references public.cajas_turno(id) on delete set null;

create table if not exists public.compras_proveedores (
  id bigint generated by default as identity primary key,
  gimnasio_id uuid not null references public.gimnasios(id) on delete cascade,
  proveedor_id bigint references public.proveedores(id) on delete set null,
  producto_id bigint references public.productos(id) on delete set null,
  cantidad integer not null check (cantidad > 0),
  costo_unitario numeric(12,2) not null default 0,
  fecha_compra timestamptz not null default now(),
  usuario_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.configuracion_mensualidad (
  id bigint generated by default as identity primary key,
  gimnasio_id uuid not null references public.gimnasios(id) on delete cascade,
  nombre_plan text not null,
  monto numeric(12,2) not null default 0,
  dias_vigencia integer not null default 30,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notificaciones (
  id bigint generated by default as identity primary key,
  gimnasio_id uuid not null references public.gimnasios(id) on delete cascade,
  usuario_id uuid references auth.users(id) on delete cascade,
  titulo text not null,
  mensaje text not null,
  tipo text not null default 'info',
  leida boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.auditoria_eventos (
  id bigint generated by default as identity primary key,
  gimnasio_id uuid references public.gimnasios(id) on delete set null,
  usuario_id uuid references auth.users(id) on delete set null,
  entidad text not null,
  entidad_id text,
  accion text not null,
  datos jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_miembros_gimnasio_estado on public."Miembros"(gimnasio_id, estado);
create index if not exists idx_perfiles_user_id on public.perfiles(user_id);
create index if not exists idx_perfiles_gimnasio_rol on public.perfiles(gimnasio_id, rol);
create index if not exists idx_pagos_gimnasio_fecha on public.pagos(gimnasio_id, fecha_pago desc);
create index if not exists idx_asistencias_gimnasio_fecha on public.asistencias(gimnasio_id, fecha desc);
create index if not exists idx_productos_gimnasio_activo on public.productos(gimnasio_id, activo);
create index if not exists idx_ventas_gimnasio_fecha on public.ventas(gimnasio_id, created_at desc);
create index if not exists idx_cajas_turno_lookup on public.cajas_turno(gimnasio_id, usuario_id, fecha, turno);

create or replace trigger trg_gimnasios_updated_at before update on public.gimnasios for each row execute function public.set_updated_at();
create or replace trigger trg_miembros_updated_at before update on public."Miembros" for each row execute function public.set_updated_at();
create or replace trigger trg_perfiles_updated_at before update on public.perfiles for each row execute function public.set_updated_at();
create or replace trigger trg_solicitudes_acceso_updated_at before update on public.solicitudes_acceso for each row execute function public.set_updated_at();
create or replace trigger trg_pagos_updated_at before update on public.pagos for each row execute function public.set_updated_at();
create or replace trigger trg_productos_updated_at before update on public.productos for each row execute function public.set_updated_at();
create or replace trigger trg_proveedores_updated_at before update on public.proveedores for each row execute function public.set_updated_at();
create or replace trigger trg_ventas_updated_at before update on public.ventas for each row execute function public.set_updated_at();
create or replace trigger trg_facturas_updated_at before update on public.facturas for each row execute function public.set_updated_at();
create or replace trigger trg_cajas_turno_updated_at before update on public.cajas_turno for each row execute function public.set_updated_at();
create or replace trigger trg_configuracion_mensualidad_updated_at before update on public.configuracion_mensualidad for each row execute function public.set_updated_at();
